"""Добавлены поля для пользователя

Revision ID: bce97847fd33
Revises: b4fd169a2479
Create Date: 2025-10-11 11:05:02.988167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce97847fd33'
down_revision: Union[str, Sequence[str], None] = 'b4fd169a2479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('password_hashed', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('salt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'salt')
    op.drop_column('user_table', 'password_hashed')
    # ### end Alembic commands ###
