"""Добавление таблицы понравившихся жанров

Revision ID: de197f4f7c09
Revises: 7a750d95f9ec
Create Date: 2025-10-12 15:05:52.293398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de197f4f7c09'
down_revision: Union[str, Sequence[str], None] = '7a750d95f9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_user_genre',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Id_user', sa.Integer(), nullable=False),
    sa.Column('Id_genre', sa.Integer(), nullable=False),
    sa.Column('datetime_favorite', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['Id_genre'], ['genre_table.genre_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Id_user'], ['user_table.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_user_genre')
    # ### end Alembic commands ###
