"""Добавлен поле роли для пользователя

Revision ID: e3428a0a35af
Revises: ed1e484c49a6
Create Date: 2025-10-11 14:08:19.145925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3428a0a35af'
down_revision: Union[str, Sequence[str], None] = 'ed1e484c49a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_table_role_key'), 'user_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_table_role_key'), 'user_table', ['role'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
