"""Добавлен поле роли для пользователя

Revision ID: 1ce50d96ee7a
Revises: e3428a0a35af
Create Date: 2025-10-11 14:10:44.566797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce50d96ee7a'
down_revision: Union[str, Sequence[str], None] = 'e3428a0a35af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
