"""Добавлены жанры и авторы

Revision ID: 26a8f73f2115
Revises: 915730f6a91c
Create Date: 2025-10-11 07:28:25.203803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a8f73f2115'
down_revision: Union[str, Sequence[str], None] = '915730f6a91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GenreTable',
    sa.Column('GenreId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GenreName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('GenreId'),
    sa.UniqueConstraint('GenreName')
    )
    op.create_table('author_table',
    sa.Column('IdAuthor', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('IdAuthor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_table')
    op.drop_table('GenreTable')
    # ### end Alembic commands ###
