"""Создание базы данных

Revision ID: 915730f6a91c
Revises: 
Create Date: 2025-10-11 07:23:06.539316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915730f6a91c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BooksTable',
    sa.Column('BookId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BookName', sa.String(), nullable=True),
    sa.Column('YearCreate', sa.Date(), nullable=True),
    sa.Column('GenreId', sa.Integer(), nullable=True),
    sa.Column('SaledBooks', sa.Integer(), nullable=True),
    sa.Column('ImageBooks', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('BookId')
    )
    op.create_table('user_table',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_user', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    op.drop_table('BooksTable')
    # ### end Alembic commands ###
