"""Связывание жанров и авторов с таблицей книг часть 2

Revision ID: b4fd169a2479
Revises: 5760a85a61e2
Create Date: 2025-10-11 07:48:52.879625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fd169a2479'
down_revision: Union[str, Sequence[str], None] = '5760a85a61e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_author',
    sa.Column('id_bool_author', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['author_table.IdAuthor'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_book'], ['books_Table.BookId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_bool_author')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_author')
    # ### end Alembic commands ###
