"""Добавление инициалов пользователя

Revision ID: a1332e7cf7da
Revises: c7ca58e60b55
Create Date: 2026-03-03 16:13:25.423437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1332e7cf7da'
down_revision: Union[str, Sequence[str], None] = 'c7ca58e60b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author_table', 'photo',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.add_column('user_table', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('last_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'last_name')
    op.drop_column('user_table', 'first_name')
    op.alter_column('author_table', 'photo',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
